name: Gitee repos mirror periodic job
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout codes'
      uses: actions/checkout@v1
    - name: Get Git Log
      id: git_log
      uses: Edisonboy/latest-git-log-action@main
      with:
        tag: origin/master
    - name: 'echo'
      run: echo ${{steps.git_log.outputs.log}}
    - name: Send email
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.qq.com
        server_port: 465
        username: ${{secrets.MAIL_USERNAME}}
        password: ${{secrets.MAIL_PASSWORD}}
        subject: Github Actions job result
        to: ${{secrets.MAIL_TOUSERNAME}}
        from: Luke Skywalker # <user@example.com>
        body: Build job of ${{github.repository}} completed successfully! ${{steps.git_log.outputs.log}}
